In [1]:
# visualisation
import matplotlib.pyplot as plt

# data analysis
import numpy as np
import pandas as pd
import mglearn
from sklearn.datasets import load_iris

In [2]:
iris_dataset = load_iris()

We have just loaded the Iris dataset from the scikit-learn library. Now we can begin to explore this datset to better understand how to visualise it.

In [3]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

Keys of iris_dataset: 
dict_keys([&#39;data&#39;, &#39;target&#39;, &#39;frame&#39;, &#39;target_names&#39;, &#39;DESCR&#39;, &#39;feature_names&#39;, &#39;filename&#39;])


In [4]:
print(iris_dataset['DESCR'][:490] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
       
...


In [5]:
print("Target names: {}".format(iris_dataset['target_names']))

Target names: [&#39;setosa&#39; &#39;versicolor&#39; &#39;virginica&#39;]


In [6]:
print("Feature names: \n{}".format(iris_dataset['feature_names']))

Feature names: 
[&#39;sepal length (cm)&#39;, &#39;sepal width (cm)&#39;, &#39;petal length (cm)&#39;, &#39;petal width (cm)&#39;]


What we now understand so far from the dataset:
* we have 3 targets, 'setosa' 'versicolor' 'virginica'
* we have 4 features, all expressed in the same unit (cm)


In [7]:
print("Data type: {}".format(type(iris_dataset['data'])))

Type of data: &lt;class &#39;numpy.ndarray&#39;&gt;


In [8]:
print("Data shape: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


In [10]:
print("First five columns of data:\n{}".format(iris_dataset['data'][:5]))

First five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [11]:
print("Data type: {}".format(type(iris_dataset['target'])))

Type of target: &lt;class &#39;numpy.ndarray&#39;&gt;


In [12]:
print("Data shape: {}".format(iris_dataset['target'].shape))

Shape of target: (150,)


In [13]:
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


This output can be made sense of by refering to the iris['target_names'] array:
0 means setosa, 1 means versicolor, and 2 means virginica